### ISSUE TITLE
Version 1.0.6 seems to break things for me

### ISSUE THREAD

**Issue by iamraffe** [bakerface/react-native-svg-web#12]
It seems like going from

`import { createElement as createReactElement } from "react";`

To 

`import { createElement as createReactElement } from "react-native-web";`

Breaks a current build I have with error:

`TypeError: (0 , _reactNativeWeb.unstable_createElement) is not a function`

Not sure whether it's something that's just happening to me, and I forced version 1.0.5 and everything went back to normal. However decided to report just in case!

Thanks!

**Comment by bakerface** [comment]
hey @iamraffe sorry to hear about the issues. I would like to work on a fix, but I can't seem to reproduce the issue. Do you mind linking me to your project (assuming it is public) or creating a sandbox that reproduces the issue?

**Comment by bakerface** [comment]
I provided a fallback in a v1.0.7 release. It should fix this issue. I am going to close this issue but feel free to reach out again if the problem persists.

**Comment by iamraffe** [comment]
Hi, sorry didn't get a notif for your response. I will try v1.0.7 and if the issue persists will try to reproduce in sandbox.

Thanks @bakerface !
